name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: | 
        Thanks for taking the time to fill out this bug report! 🙌
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you experience
    validations:
      required: true
  - type: input
    id: demo
    attributes:
      label: Demo/example
      description: Please provide a code sample or a demo where we'll be able to replicate the issue
  - type: dropdown
    id: support-type
    attributes:
      description: Do you already has a license for Handsontable?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: On which browser/OS is the issue replicable?
  - type: input
    id: version-hot
    attributes:
      label: Which Handsontable version do you use?    

