name: Bug Report
description: Did you find a bug 🐛? Please report, and help us to solve it faster. 
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: | 
        Thanks for taking the time to fill out this bug report! 🙌
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please provide the description of the actual and the expected result
    validations:
      required: true
  - type: textarea
    id: required-steps
    attributes:
      label: How to recreate the issue?
      description: Please provide the ordered steps of how to recreate the issue
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Video/Screenshots
      description: Please provide the a screenshot or a short video presenting the issue
    validations:
      required: true
  - type: input
    id: demo
    attributes:
      label: Demo/example
      description: Please provide a code sample or a demo so we can replicate the issue
    validations:
      required: true
  - type: dropdown
    id: support-type
    attributes:
      label: Support Type
      description: Do you already have a license for Handsontable?
      multiple: true
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: browsers
    attributes:
      label: On which browser and OS did the issue occur?
  - type: input
    id: version-hot
    attributes:
      label: Which Handsontable version do you use?
  - type: input
    id: framework
    attributes:
      label: What framework do you use?

