name: Issue Report
description: Something is broken? Create a report to help us improve. 
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what happens and the steps to recreate the problem.
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals :dart:
      description: TODO
  - type: input
    id: reference
    attributes:
      label: Reference :left_right_arrow:
      description: Use StackBlitz, CodeSandbox, CodePen, JSFiddle, or any other online sandbox.
  - type: textarea
    id: todo
    attributes:
      label: Tasks to do :white_check_mark:
      description: TODO
  - type: textareas
    id: delivery
    attributes:
      label: Delivery :truck:
      description: TODO
  - type: textarea
    id: questions
    attributes:
      label: Doubts and questions :question:
      description: TODO

