name: Improve documentation
description: Suggest an improvement to the docs.
body:
  - type: input
    id: link
    attributes:
      label: Page URL
      description: Which page are you referring to?
      placeholder: https://handsontable.com/docs/…
  - type: textarea
    id: improvement
    attributes:
      label: Improvement description
