name: Typo Report
description: Did you find a typo or a discrepancy in the documentation? Let us know 📄
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: link
    attributes:
      label: Link to the typo/discrepancy
      description: Please provide the link
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Share a screenshot and describe the issue
      description: Tell us what the mistake is
  - type: textarea
    id: result
    attributes:
      label: Expected correction
      description: Please provide the expected correction
