name: Typo Report
description: Did you find a typo or a discrepency in the documentation? Let us know 📄
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: link
    attributes:
      label: Link to a the typo/discrepency
      description: Please provide the link
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Share a screenshot
      description: Share a screenshot of the found typo/discrepency so it is easier to find it or descibe the location of the issue
  - type: textarea
    id: result
    attributes:
      label: Expected result
      description: Provide the description of a expected result
